"use client";
import {useState,useRef,useEffect,FormEvent} from 'react';
import {Play,Pause,Volume2,VolumeX,MessageCircle,Check,X,ShieldCheck} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
type Media={film?:string;voice?:string;music?:string;segments:{start:number;end:number}[];videos?:Record<string,string>;sfx?:Record<string,string>};
const priorities=[['result','نتیجهٔ موردنظر','این‌که به نیاز من پاسخ بده'],['quality','کیفیت محصول','این‌که چه چیزی انتخاب می‌کنم'],['price','قیمت مناسب','این‌که با بودجه‌ام جور باشه']];
const approaches=[['try','اول امتحانش کنم','اگر امکان امتحان‌کردن داشته باشه'],['experience','تجربهٔ دیگران رو ببینم','تجربهٔ واقعی استفاده‌کننده‌ها'],['difference','تفاوت‌ها رو بررسی کنم','ویژگی‌ها، کاربرد و شیوهٔ استفاده']];
const photos=['s01-before-you-buy.png','s02-purchase-table.png','s02-purchase-table.png','s03-material-details.png','s03-material-details.png','s04-friendly-consultation.png'];
const transcripts=['تا حالا چیزی خریدی که همه می‌گفتن عالیه… ولی برای تو هیچ فرقی نکرد؟ شاید مسئله، فقط خود محصول نبوده.','چیزی که برای یکی فوق‌العاده‌ست، ممکنه چیزی نباشه که تو لازم داری. بذار اول بفهمیم تو چی می‌خوای.','وقتی می‌خوای یه محصول جدید بخری، کدوم برات مهم‌تره؟ نتیجه‌ای که می‌گیری، کیفیت محصول، یا قیمت مناسب؟','حالا یه سؤال دیگه. برای این‌که بفهمی یه محصول به دردت می‌خوره، ترجیح می‌دی اول امتحانش کنی، تجربهٔ بقیه رو ببینی، یا بفهمی چرا متفاوته؟','می‌شه اول محصول رو دید، بعد دنبال دلیل گشت که چرا باید خریدش. بیا این بار از نیاز تو شروع کنیم. اول نیازت، بعد بررسی محصول، آخرش هم تصمیم با خودت.','اگه هنوز مطمئن نیستی چی برای نیاز تو مناسبه، یه گفت‌وگوی کوتاه می‌تونه شروع خوبی باشه. روی «نیاز به مشاوره دارم» بزن.'];
function requestId(){
 const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;
 const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;
}
export default function Page(){
 const [step,setStep]=useState(-1),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[ready,setReady]=useState(false),[progress,setProgress]=useState(0),[captions,setCaptions]=useState(false);
 const [priority,setPriority]=useState(''),[approach,setApproach]=useState(''),[form,setForm]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[consent,setConsent]=useState(false),[trap,setTrap]=useState('');
 const [saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[media,setMedia]=useState<Media>({segments:[]}),[audioIssue,setAudioIssue]=useState(false);
 const voice=useRef<HTMLAudioElement>(null),music=useRef<HTMLAudioElement>(null),video=useRef<HTMLVideoElement>(null),cue=useRef<{start:number;end:number}|undefined>(undefined),id=useRef(''),lock=useRef(false);
 const scene=Math.max(0,Math.min(step,5));const filmMode=!!media.film&&step>=0;const holdFrame=filmMode&&((step===2&&(ready||progress>=94))||(step===3&&(ready||progress>=96))||(step===5&&(ready||progress>=94)))?step===2?'q1-hold.jpg':step===3?'q2-hold.jpg':'cta-hold.jpg':undefined;
 useEffect(()=>{fetch('/media.json').then(r=>r.json()).then(data=>setMedia(data as Media)).catch(()=>setAudioIssue(true));},[]);
 function fx(kind:string){if(muted||!media.sfx?.[kind])return;const a=new Audio(media.sfx[kind]);a.volume=.18;void a.play().catch(()=>{});}
 function playCue(n:number){setReady(false);setPaused(false);setProgress(0);cue.current=media.segments[n];const a=media.film?video.current:voice.current;if(a&&cue.current){a.currentTime=cue.current.start;void a.play().catch(()=>{setAudioIssue(true);setReady(true);});}else setReady(true);}
 function move(n:number){fx('transition');setStep(n);playCue(n);}
 function begin(){setSaved(false);setError('');setName('');setPhone('');setConsent(false);setPriority('');setApproach('');id.current=requestId();move(0);if(!media.film)void music.current?.play().catch(()=>{});}
 function tick(){const a=media.film?video.current:voice.current,c=cue.current;if(!a||!c)return;setProgress(Math.max(0,Math.min(100,(a.currentTime-c.start)/(c.end-c.start)*100)));if(a.currentTime>=c.end-(media.film?.08:0)){if(media.film&&!form&&[0,1,4].includes(step)){cue.current=media.segments[step+1];setStep(step+1);setProgress(0);return;}a.pause();if(media.film&&a.currentTime>c.end-.05)a.currentTime=c.end-.08;setReady(true);setProgress(100);}}
 useEffect(()=>{if(voice.current)voice.current.muted=muted;if(video.current&&media.film)video.current.muted=muted;if(music.current){music.current.muted=muted;music.current.volume=ready?.035:.085;}},[muted,ready,media.film]);
 useEffect(()=>{if(!ready||paused||form||step<0||[2,3,5].includes(step))return;const timer=setTimeout(()=>move(step+1),700);return()=>clearTimeout(timer);},[ready,paused,form,step]);
 useEffect(()=>{const stop=()=>{if(document.hidden){voice.current?.pause();music.current?.pause();video.current?.pause();setPaused(true);}};document.addEventListener('visibilitychange',stop);return()=>document.removeEventListener('visibilitychange',stop);},[]);
 function toggle(){if(ready)return;const a=media.film?video.current:voice.current;if(paused){void a?.play().catch(()=>setAudioIssue(true));if(!media.film)void music.current?.play().catch(()=>{});}else{a?.pause();music.current?.pause();}setPaused(!paused);}
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||saved)return;setError('');if(!consent){setError('برای ثبت درخواست، اجازهٔ تماس را مشخص کن.');return;}lock.current=true;setSaving(true);id.current ||= requestId();try{const r=await fetch('/api/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,priority,approach,consent,requestId:id.current,website:trap})});const d=await r.json() as {ok?:boolean;error?:string};if(!r.ok||!d.ok)throw new Error(d.error||'ثبت انجام نشد. دوباره تلاش کن.');setSaved(true);voice.current?.pause();video.current?.pause();fx('success');}catch(e){setError(e instanceof Error?e.message:'ارتباط برقرار نشد؛ دوباره تلاش کن.');}finally{lock.current=false;setSaving(false);}}
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'read_consultation_journey',description:'Read visible journey state and preferences. No contact data submission.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({step,priority,approach,formOpen:form,registered:saved})},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[step,priority,approach,form,saved]);
 const choiceList=step===2?priorities:approaches,choice=step===2?priority:approach;
 return <main className="experience" dir="rtl"><div className="ambient"/><section className={`stage stage-${scene} ${filmMode?'film-mode':''}`} aria-label="مشاوره پیش از خرید">
 <div className="scene-image"><img src={`/assets/${photos[scene]}`} alt=""/>{media.film?<video aria-label="فیلم فارسی مشاوره پیش از خرید" ref={video} src={media.film} muted={muted} playsInline preload="auto" className={step<0?'film-hidden':''} onTimeUpdate={tick} onEnded={()=>setReady(true)} onError={()=>{setMedia(m=>({...m,film:undefined}));setAudioIssue(true);}}/>:step>=0&&media.videos?.[String(scene)]&&<video ref={video} src={media.videos[String(scene)]} autoPlay muted loop playsInline/>}{holdFrame&&<img className="question-hold" src={`/assets/${holdFrame}`} alt=""/>}</div><div className="shade"/>
 <header className="topbar" inert={form}><span className="wordmark"><i/>پیش از خرید</span><span className="small-label">با شناخت انتخاب کن</span><button className="icon-button" onClick={()=>setMuted(!muted)} aria-label={muted?'روشن‌کردن صدا':'بی‌صدا کردن'}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</button></header>
 {step>=0&&!form&&<div className="journey-progress" aria-label={`مرحلهٔ ${step+1} از ۶`}>{[0,1,2,3,4,5].map(i=><Progress key={i} value={i<step?100:i===step?progress:0} className="chapter-progress"/>)}</div>}
 <div className={`story story-${scene} ${filmMode?'film-controls':''}`} key={step} inert={form} aria-hidden={form}>
 {(step===-1||(step===0&&!filmMode))&&<><div className="eyebrow">{step<0?'یک تجربهٔ کوتاه، قبل از خرید':'اون خرید آشنا…'}</div><h1>همه می‌گفتن<br/><em>عالیه.</em><br/><span>برای تو چی؟</span></h1>{step<0?<div className="start-bottom"><p>بیا از چیزی شروع کنیم<br/>که تو لازم داری.</p><button className="primary" disabled={!media.segments.length} onClick={begin}><Play size={19} fill="currentColor"/>{media.segments.length?'برای شروع کلیک کن':'در حال آماده‌سازی…'}</button><span className="meta">دو سؤال کوتاه · انتخاب با تو</span></div>:<div className="bottom-type">شاید مسئله،<br/><strong>فقط خودِ محصول نبوده.</strong></div>}</>}
 {step===1&&!filmMode&&<><div className="eyebrow">قبل از معرفی هر محصول</div><h2>اول،<br/><em>نیازِ تو.</em></h2><div className="bottom-type">چیزی که برای یکی عالیه،<br/>ممکنه انتخاب تو نباشه.</div></>}
 {[2,3].includes(step)&&<><div className="eyebrow">سؤال {step===2?'۱':'۲'} از ۲</div><h2>{step===2?<>چی برات<br/><em>مهم‌تره؟</em></>:<>چطور<br/><em>مطمئن‌تر می‌شی؟</em></>}</h2><RadioGroup className={`choices ${filmMode?'film-hotspots':''}`} value={choice} onValueChange={v=>{if(step===2)setPriority(v);else setApproach(v);fx('select');}} aria-label={step===2?'اولویت خرید':'روش بررسی محصول'}>{choiceList.map((x,i)=><label className={`choice ${choice===x[0]?'selected':''}`} htmlFor={`${step}-${x[0]}`} key={x[0]}><span className="choice-num">{['۰۱','۰۲','۰۳'][i]}</span><span><strong>{x[1]}</strong><small>{x[2]}</small></span><RadioGroupItem id={`${step}-${x[0]}`} value={x[0]}/></label>)}</RadioGroup><button className="primary continue" disabled={!choice||!ready} onClick={()=>move(step+1)}>{ready?'برای ادامه کلیک کن':'به سؤال گوش کن…'}</button></>}
 {step===4&&!filmMode&&<><div className="eyebrow">این بار، از خودت شروع کن</div><h2>خرید از<br/><em>شناخت شروع می‌شه.</em></h2><div className="process">{['نیاز تو','بررسی محصول','تصمیم خودت'].map((t,i)=><div key={t}><b>{['۰۱','۰۲','۰۳'][i]}</b><span>{t}</span></div>)}</div><img className="cutout" src="/assets/t02-brass-magnifying-glass.png" alt="ذره‌بین برای بررسی دقیق‌تر"/></>}
 {step===5&&<><div className="eyebrow">مشاوره پیش از خرید</div><h2>یه گفت‌وگوی کوتاه.<br/><em>برای انتخاب تو.</em></h2><div className={`cta-bottom ${filmMode&&progress<69&&!ready?'cta-waiting':''}`}><div className="preference-summary"><span>ترجیحات تو برای گفت‌وگو</span><strong>{priorities.find(x=>x[0]===priority)?.[1]} <i>·</i> {approaches.find(x=>x[0]===approach)?.[1]}</strong></div><button className="primary consultation-trigger" disabled={filmMode&&progress<69&&!ready} onClick={()=>{fx('select');setForm(true);playCue(6);}}><MessageCircle size={21}/>نیاز به مشاوره دارم</button><button className="text-button" onClick={()=>{voice.current?.pause();video.current?.pause();music.current?.pause();setStep(-1);setReady(false);}}>فعلاً نه</button></div></>}
 </div>
 {step>=0&&!form&&<footer className="playback"><button className="icon-button" onClick={toggle} disabled={ready} aria-label={paused?'ادامهٔ پخش':'توقف پخش'}>{paused||ready?<Play size={18}/>:<Pause size={18}/>}</button><span>{ready?([2,3].includes(step)?'انتخاب کن؛ ادامه با توست':'ادامهٔ مسیر…'):paused?'برای ادامه کلیک کن':'لمس کن تا مکث کنیم'}</span><button className={`caption-toggle ${captions?'active':''}`} onClick={()=>setCaptions(!captions)} aria-label="نمایش متن گفتار" aria-pressed={captions}>متن</button></footer>}
 {captions&&step>=0&&!form&&<div className="spoken-text" role="region" aria-label="متن گفتار">{transcripts[step]}</div>}
 {audioIssue&&step>=0&&!form&&<button className="audio-recovery" onClick={()=>{setAudioIssue(false);playCue(step);}}>برای پخش صدا لمس کن</button>}
 {form&&<div className="form-surface" role="dialog" aria-modal="true" aria-label="درخواست مشاوره"><div className="form-top"><span className="eyebrow">مشاوره پیش از خرید</span>{!saved&&<button className="icon-button" aria-label="بستن فرم" onClick={()=>{setForm(false);voice.current?.pause();video.current?.pause();if(media.film&&video.current)video.current.currentTime=60.6;setReady(true);setTimeout(()=>document.querySelector<HTMLButtonElement>('.consultation-trigger')?.focus(),0);}}><X size={22}/></button>}</div>{saved?<div className="success" role="status"><span className="success-icon"><Check size={42}/></span><h2>درخواستت<br/><em>ثبت شد.</em></h2><p>{name.trim()}، نام و شماره‌ات همراه ترجیحاتت ثبت شد.</p><span className="meta">ثبت درخواست به معنی تعیین زمان مشاوره نیست.</span><button className="text-button" onClick={()=>{setForm(false);setStep(-1);video.current?.pause();music.current?.pause();}}>بازگشت به شروع</button></div>:<><h2>از همین‌جا<br/><em>شروع کنیم.</em></h2><p className="form-intro">نام و شماره‌ات را برای درخواست مشاوره بنویس.</p><form onSubmit={submit}><label className="field">نام<input name="name" autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={80} placeholder="نام شما"/></label><label className="field">شماره موبایل<input name="phone" autoComplete="tel" inputMode="tel" dir="ltr" value={phone} onChange={e=>setPhone(e.target.value)} required maxLength={20} placeholder="۰۹۱۲ ۱۲۳ ۴۵۶۷"/></label><label className="trap" aria-hidden="true">وب‌سایت<input name="website" tabIndex={-1} autoComplete="off" value={trap} onChange={e=>setTrap(e.target.value)}/></label><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="اجازهٔ تماس برای مشاوره"/><span>با ثبت این درخواست، اجازه می‌دهم برای همین مشاوره با من تماس بگیرید.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={saving}>{saving?'در حال ثبت…':'ثبت درخواست مشاوره'}</button><p className="privacy-note"><ShieldCheck size={17}/>اطلاعاتت برای همین درخواست ثبت می‌شود.</p></form></>}</div>}
 <audio ref={voice} src={media.voice} preload="auto" onTimeUpdate={tick} onEnded={()=>setReady(true)}/><audio ref={music} src={media.music} preload="auto" loop/>
 </section><aside className="desktop-note"><span>قبل از اینکه بخری</span><p>اول نیاز تو.<br/>بعد انتخاب تو.</p><small>مشاوره پیش از خرید</small></aside></main>;
}
